-- MySQL Script generated by MySQL Workbench
-- Tue Dec 19 08:30:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema marcel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marcel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marcel` DEFAULT CHARACTER SET utf8 ;
USE `marcel` ;

-- -----------------------------------------------------
-- Table `marcel`.`T_USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcel`.`T_USERS` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(50) NULL,
  `PRENOM` VARCHAR(50) NULL,
  `MAIL` VARCHAR(250) NULL,
  `PASSWORD` CHAR(40) NULL,
  PRIMARY KEY (`ID_USER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcel`.`T_LIVRAISONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcel`.`T_LIVRAISONS` (
  `ID_LIVRAISON` INT NOT NULL AUTO_INCREMENT,
  `DESIGNATION` VARCHAR(45) NULL,
  `RUE` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `VILLE` VARCHAR(45) NULL,
  `T_USERS_ID_USER` INT NOT NULL,
  `DEFAUT` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_LIVRAISON`, `T_USERS_ID_USER`),
  INDEX `fk_T_LIVRAISONS_T_USERS1_idx` (`T_USERS_ID_USER` ASC),
  CONSTRAINT `fk_T_LIVRAISONS_T_USERS1`
    FOREIGN KEY (`T_USERS_ID_USER`)
    REFERENCES `marcel`.`T_USERS` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcel`.`T_PRODUITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcel`.`T_PRODUITS` (
  `ID_PRODUIT` INT NOT NULL AUTO_INCREMENT,
  `REFERENCE` VARCHAR(45) NULL,
  `PHOTO` VARCHAR(45) NULL,
  `PUHT` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PRODUIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marcel`.`T_COMMANDES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcel`.`T_COMMANDES` (
  `T_PRODUITS_ID_PRODUIT` INT NOT NULL,
  `T_USERS_ID_USER` INT NOT NULL,
  `REFERENCE` VARCHAR(45) NULL,
  `PTHT` VARCHAR(45) NULL,
  `PTTTC` VARCHAR(45) NULL,
  PRIMARY KEY (`T_PRODUITS_ID_PRODUIT`, `T_USERS_ID_USER`),
  INDEX `fk_T_PRODUITS_has_T_USERS_T_USERS1_idx` (`T_USERS_ID_USER` ASC),
  INDEX `fk_T_PRODUITS_has_T_USERS_T_PRODUITS1_idx` (`T_PRODUITS_ID_PRODUIT` ASC),
  CONSTRAINT `fk_T_PRODUITS_has_T_USERS_T_PRODUITS1`
    FOREIGN KEY (`T_PRODUITS_ID_PRODUIT`)
    REFERENCES `marcel`.`T_PRODUITS` (`ID_PRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_PRODUITS_has_T_USERS_T_USERS1`
    FOREIGN KEY (`T_USERS_ID_USER`)
    REFERENCES `marcel`.`T_USERS` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
