-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 17:20:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema maurice
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maurice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maurice` DEFAULT CHARACTER SET utf8 ;
USE `maurice` ;

-- -----------------------------------------------------
-- Table `maurice`.`T_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maurice`.`T_USER` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `PRENOM` VARCHAR(45) NULL,
  `MAIL` VARCHAR(200) NULL,
  `PASSWORD` CHAR(40) NULL,
  PRIMARY KEY (`ID_USER`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maurice`.`ID_ADRESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maurice`.`ID_ADRESS` (
  `ID_ADRESS` INT NOT NULL AUTO_INCREMENT,
  `NUM` DECIMAL(4) NULL,
  `RUE` VARCHAR(45) NULL,
  `CODE POSTAL` DECIMAL(6) NULL,
  `VILLE` VARCHAR(45) NULL,
  `DESIGNATION` VARCHAR(45) NULL,
  `T_USER_ID_USER` INT NOT NULL,
  PRIMARY KEY (`ID_ADRESS`, `T_USER_ID_USER`),
  INDEX `fk_ID_ADRESS_T_USER1_idx` (`T_USER_ID_USER` ASC),
  CONSTRAINT `fk_ID_ADRESS_T_USER1`
    FOREIGN KEY (`T_USER_ID_USER`)
    REFERENCES `maurice`.`T_USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maurice`.`ID_PRODUIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maurice`.`ID_PRODUIT` (
  `ID_PRODUIT` INT NOT NULL AUTO_INCREMENT,
  `REFERENCE` VARCHAR(45) NULL,
  `PHOTO` VARCHAR(45) NULL,
  `PRIX_HT` FLOAT NULL,
  PRIMARY KEY (`ID_PRODUIT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maurice`.`ID_CMD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maurice`.`ID_CMD` (
  `ID_PRODUIT_ID_PRODUIT` INT NOT NULL,
  `T_USER_ID_USER` INT GENERATED ALWAYS AS () VIRTUAL,
  `REFERENCE` VARCHAR(45) NULL,
  `PRIX_TOTAL_TTC` VARCHAR(45) NULL,
  `PRIX_TTC` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PRODUIT_ID_PRODUIT`, `T_USER_ID_USER`),
  INDEX `fk_ID_PRODUIT_has_T_USER_T_USER1_idx` (`T_USER_ID_USER` ASC),
  INDEX `fk_ID_PRODUIT_has_T_USER_ID_PRODUIT1_idx` (`ID_PRODUIT_ID_PRODUIT` ASC),
  CONSTRAINT `fk_ID_PRODUIT_has_T_USER_ID_PRODUIT1`
    FOREIGN KEY (`ID_PRODUIT_ID_PRODUIT`)
    REFERENCES `maurice`.`ID_PRODUIT` (`ID_PRODUIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ID_PRODUIT_has_T_USER_T_USER1`
    FOREIGN KEY (`T_USER_ID_USER`)
    REFERENCES `maurice`.`T_USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
