-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 14:49:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Nfactoryschool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Nfactoryschool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Nfactoryschool` DEFAULT CHARACTER SET utf8 ;
USE `Nfactoryschool` ;

-- -----------------------------------------------------
-- Table `Nfactoryschool`.`T_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nfactoryschool`.`T_users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(50) NULL,
  `Mail` VARCHAR(250) NULL,
  `PSD` CHAR(50) NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nfactoryschool`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nfactoryschool`.`commande` (
  `idcommande` INT NOT NULL,
  `Ref` VARCHAR(45) NULL,
  `date` DATE NULL,
  `T_users_id_users` INT NOT NULL,
  PRIMARY KEY (`idcommande`, `T_users_id_users`),
  INDEX `fk_commande_T_users_idx` (`T_users_id_users` ASC),
  CONSTRAINT `fk_commande_T_users`
    FOREIGN KEY (`T_users_id_users`)
    REFERENCES `Nfactoryschool`.`T_users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
